micronaut:
  application:
    name: mn-oci-elasticsearch-demo
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
elasticsearch:
  httpHosts:
    - "http://localhost:9200"
  cluster:
    name:
  request:
    default:
      authentication-enabled: false
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
codes:
  recursive:
    elasticsearch:
      index:
        name:
        type: